WhiteLagoon/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Implementation;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;

        public VillaController(IVillaService villaService)
        {
            _villaService = villaService;
        }


        public IActionResult Index()
        {
            var villas = _villaService.GetAllVillas();  
            return View(villas);
        }
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        public IActionResult Create(Villa obj)
        {

            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("", "Name can't be the same as Description");
            }
            if(ModelState.IsValid) {    
               bool sucessCreate = _villaService.CreateVilla(obj);
                if (sucessCreate)
                {
                    TempData["success"] = "Villa is Created successfuly . ";
                    return RedirectToAction(nameof(Index));

                }     
            }

            TempData["error"] = "can't  Created Villa ";
            return View(obj);
          
        }

        #region update
        public IActionResult Update(int VillaId)
        {
            Villa? obj = _villaService.GetVillaById(VillaId);
            if (obj == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View("Update", obj);

        }
        [HttpPost]
        public IActionResult Update(Villa obj)
        {

            if (ModelState.IsValid)
            {
                bool villaUpdated = _villaService.UpdateVilla(obj);
                if (villaUpdated)
                {
                   TempData["success"] = "Villa is updated successfuly . ";
                   return RedirectToAction(nameof(Index));
                }
             
            }
            TempData["error"] = "Villa can't be update ";
            return View(obj);

        }

        #endregion
     
        public IActionResult Delete(int VillaId)
        {
            Villa? obj = _villaService.GetVillaById(VillaId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View( obj);

        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {

            bool villaDeleted = _villaService.DeleteVilla(obj.Id);
            if (villaDeleted)
            {
                TempData["success"] = "the villa has been deleted successfuly";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                TempData["error"] = "the villa can't be deleted";
                return View(obj);
            }
           

        }

    }
}

WhiteLagoon/Views/Villa/Create.cshtml
@model Villa
@{
    ViewData["Title"] = "Create";
}

<div class="w-100 card border-0 p-4">
    <!-- Card Header -->
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>

    <!-- Card Body -->
    <div class="card-body border p-4">
        <form method="post" asp-action="Create" asp-controller="Villa" class="row" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="p-3">
                <!-- Name -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Name" class="form-control border shadow" />
                    <label asp-for="@Model.Name" class="ms-2"></label>
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                <!-- Description -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Description" class="form-control border shadow" />
                    <label asp-for="@Model.Description" class="ms-2"></label>
                     <span asp-validation-for="@Model.Description" class="text-danger"></span>
                </div>

                <!-- Price -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Price" class="form-control border shadow" />
                    <label asp-for="@Model.Price" class="ms-2"></label>
                      <span asp-validation-for="@Model.Price" class="text-danger"></span>
                </div>

                <!-- Sqft -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Sqft" class="form-control border shadow" />
                    <label asp-for="@Model.Sqft" class="ms-2"></label>
                      <span asp-validation-for="@Model.Sqft" class="text-danger"></span>
                </div>

                <!-- Occupancy -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Occupancy" class="form-control border shadow" />
                    <label asp-for="@Model.Occupancy" class="ms-2"></label>
                      <span asp-validation-for="@Model.Occupancy" class="text-danger"></span>
                </div>

                <!-- Image URL -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.ImageUrl" hidden class="form-control border shadow" />
                    <input asp-for="@Model.Image"  class="form-control border shadow" />
                    <label asp-for="@Model.ImageUrl" class="ms-2"></label>
                      <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
                </div>

                <!-- Submit Button -->
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-action="index" asp-controller="Villa" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts{
      
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon/Views/Villa/Delete.cshtml
@model Villa
@{
    ViewData["Title"] = "Update";
}

<div class="w-100 card border-0 p-4">
    <!-- Card Header -->
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa</h2>
            </div>
        </div>
    </div>

    <!-- Card Body -->
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Id" hidden />
        <div class="col-10">
                <div class="p-3">
                <!-- Name -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Name" disabled class="form-control border shadow" />
                    <label asp-for="@Model.Name" class="ms-2"></label>
                </div>

                <!-- Description -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Description" disabled class="form-control border shadow" />
                    <label asp-for="@Model.Description" class="ms-2"></label>
                </div>

                <!-- Price -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Price" disabled class="form-control border shadow" />
                    <label asp-for="@Model.Price" class="ms-2"></label>
                </div>

                <!-- Sqft -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Sqft" disabled class="form-control border shadow" />
                    <label asp-for="@Model.Sqft" class="ms-2"></label>
                </div>

                <!-- Occupancy -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.Occupancy" disabled class="form-control border shadow" />
                    <label asp-for="@Model.Occupancy" class="ms-2"></label>
                      <span asp-validation-for="@Model.Occupancy" class="text-danger"></span>
                </div>

                <!-- Image URL -->
                <div class="form-floating py-2 col-12">
                    <input asp-for="@Model.ImageUrl" disabled class="form-control border shadow" />
                    <label asp-for="@Model.ImageUrl" class="ms-2"></label>
                      <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
                </div>

                <!-- Submit Button -->
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger w-100">
                            <i class="bi bi-trash-fill"></i> Delete
                        </button>
                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-action="index" asp-controller="Villa" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%
                style="border-radius:5px; border:1px; solid #bbb9b9" />
            </div>
        </form>
    </div>
</div>
@section Scripts {

    @{
                        <partial name="_ValidationScriptsPartial" />
    }
}

WhiteLagoon/Views/Villa/Index.cshtml
@model List<Villa>
@{
    ViewData["Title"] = "Index";
}

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>

    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-action="Create" asp-controller="Villa" class =" btn btn-secondary">
                   <i class="bi bi-plus-circle"></i>  Create New Villa
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Sqft</th>
                    <th>Occupancy</th>
                     <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Price</td>
                            <td>@item.Sqft</td>
                            <td>@item.Occupancy</td>
                            <td>
                                <div  class="w-75 btn-group" role="group" > 

                                        <a asp-action="Update" asp-controller="Villa" asp-route-villaId="@item.Id"
                                            class="btn btn-success mx-2">
                                            <i class="bi bi-pencil-square"></i>
                                            Edit
                                        </a>


                                        <a asp-action="Delete" asp-controller="Villa" asp-route-villaId="@item.Id"
                                            class="btn btn-danger mx-2">
                                                <i class="bi bi-trash-fill"></i>   Delete
                                          
                                        </a>
                                </div>
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WhiteLagoon/Views/Villa/update.cshtml
@model Villa
@{
    ViewData["Title"] = "Update";
}

<div class="w-100 card border-0 p-4">
    <!-- Card Header -->
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Villa</h2>
            </div>
        </div>
    </div>

    <!-- Card Body -->
    <div class="card-body border p-4">
        <form method="post" asp-action="Update" asp-controller="Villa"  class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />

            <div class="col-10">
                <div class="p-3">
                    <!-- Name -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Name" class="form-control border shadow" />
                        <label asp-for="@Model.Name" class="ms-2"></label>
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>

                    <!-- Description -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Description" class="form-control border shadow" />
                        <label asp-for="@Model.Description" class="ms-2"></label>
                         <span asp-validation-for="@Model.Description" class="text-danger"></span>
                    </div>

                    <!-- Price -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Price" class="form-control border shadow" />
                        <label asp-for="@Model.Price" class="ms-2"></label>
                          <span asp-validation-for="@Model.Price" class="text-danger"></span>
                    </div>

                    <!-- Sqft -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Sqft" class="form-control border shadow" />
                        <label asp-for="@Model.Sqft" class="ms-2"></label>
                          <span asp-validation-for="@Model.Sqft" class="text-danger"></span>
                    </div>

                    <!-- Occupancy -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Occupancy" class="form-control border shadow" />
                        <label asp-for="@Model.Occupancy" class="ms-2"></label>
                          <span asp-validation-for="@Model.Occupancy" class="text-danger"></span>
                    </div>

                    <!-- Image URL -->
                    <div class="form-floating py-2 col-12">
                        <input asp-for="@Model.Image" class="form-control border shadow" />
                        <input asp-for="@Model.ImageUrl" hidden class="form-control border shadow" />
                        <label asp-for="@Model.ImageUrl" class="ms-2"></label>
                          <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
                    </div>

                    <!-- Submit Button -->
                    <div class="row pt-2">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success w-100">
                                <i class="bi bi-check-circle"></i> Update
                            </button>
                        </div>

                        <div class="col-6 col-md-3">
                            <a asp-action="index" asp-controller="Villa" class="btn btn-secondary w-100">
                                <i class="bi bi-x-circle"></i> Cancel
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <img src="@Model.ImageUrl" width="100%
                    style="border-radius:5px; border:1px; solid #bbb9b9" />
            </div>
         
        </form>
    </div>
</div>
@section Scripts {

    @{
                <partial name="_ValidationScriptsPartial" />
    }
}