WhiteLagoon/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.CompilerServices;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Application.Utilities;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.ViewModels;

namespace WhiteLagoon.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AmenityController : Controller
    {
        private readonly IAmenityService _amenityService;
        private readonly IVillaService _villaService;


        public AmenityController(IAmenityService amenityService, IVillaService virillaService)
        {

            _amenityService = amenityService;
            _villaService = virillaService;
        }
        public IActionResult Index()
        {
            var amenities = _amenityService.GetAllAmenities(IncludeProperties:"Villa");
            return View(amenities);
        }
        #region Create
        public IActionResult Create()
        {
            AmenityVM model = new AmenityVM()
            {
                VillaList = VillaDropDownList()

            };
            return View("Create", model);
        }
        [HttpPost]
        public IActionResult Create(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                var amenityDB = new Amenity()
                {
                    Name = amenityVM.Name,
                    Description = amenityVM.Description,
                    VillaId = amenityVM.VillaId

                };
                bool created = _amenityService.CreateAmenity(amenityDB);
                if (created)
                {
                    TempData["success"] = "A new Amenity Created successfuly";
                    return RedirectToAction("Index");
                }
                
            }
            TempData["error"] = "can't create Amentiy";
            return View(amenityVM);
        } 
        #endregion
        public IActionResult Update(int ameityId)
        {
            var amentiyDB = _amenityService.GetAmenityById( ameityId);
            var amenityVM = new AmenityVM()
            {
                VillaList = VillaDropDownList(),
                Name = amentiyDB.Name,
                VillaId = amentiyDB.VillaId,
                Description = amentiyDB.Description


            };
            if (amentiyDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }

            return View(amenityVM);
        }


        [HttpPost]
        public IActionResult Update(AmenityVM amenityVM)
        {
            if(ModelState.IsValid)
            {
                var amenityDB = new Amenity()
                {
                    Name = amenityVM.Name,
                    Description = amenityVM.Description,
                    VillaId = amenityVM.VillaId,
                };
               bool updated =  _amenityService.UpdateAmenity(amenityDB);
                if (updated)
                {
                    TempData["success"] = "Amenity is updated successfuly";
                   return RedirectToAction(nameof(Index));
                }
            }
            TempData["error"] = "Can not Update Amenity";
            return View(amenityVM);


        }
        public IActionResult Delete(int villaId)
        {

            var amenityDB = _amenityService.GetAmenityById( villaId);
            var amenityVM = new AmenityVM()
            {
                VillaList = VillaDropDownList(),
                Description = amenityDB.Description,
                VillaId = amenityDB.VillaId,
                Name = amenityDB.Name,
                Id =  amenityDB.Id


            };
            if (amenityDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }
            return View(amenityVM);
        }


        [HttpPost]
        public IActionResult Delete(AmenityVM amenityVM)
        {
            bool deleted = _amenityService.DeleteAmenity(amenityVM.Id);
            if (deleted)
            {
                TempData["success"] = "Villa Number Deleted successfly";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "Can't Delete the Villa Number";
            return View(amenityVM);
        }
        private IEnumerable<SelectListItem> VillaDropDownList()
        {
            return _villaService.GetAllVillas().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });

        }

    }
    
}

WhiteLagoon/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Application.Utilities;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.ViewModels;

namespace WhiteLagoon.Controllers
{
	public class DashboardController : Controller
	{
	
        private readonly IUnitOfWork _unitOfWork;
        private readonly IDashboardService _dashboardServices;


        public DashboardController(IUnitOfWork unitOfWork, IDashboardService dashboardServices)
        {
            _unitOfWork = unitOfWork;
            _dashboardServices = dashboardServices;
        }
        public IActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> GetBookingsRedialChartData()
		{

			return Json(await _dashboardServices.GetBookingsRedialChartData());	
        }

        public async Task<IActionResult> GetUsersRedialChartData()
        {

            return Json(await _dashboardServices.GetUsersRedialChartData());
        }

        public async Task<IActionResult> GetRevenuesRedialChartData()
        {

            return Json(await _dashboardServices.GetRevenuesRedialChartData());
        }

        public async Task<IActionResult> GetCustomerBookingsPieChartData()
        {
            return Json(await _dashboardServices.GetCustomerBookingsPieChartData());    
        }

        public async Task<IActionResult> GetCustomersAndBookingLineChart()
        {

            return Json( await _dashboardServices.GetCustomersAndBookingLineChart());     
        }

        


    }
}

WhiteLagoon/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Implementation;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.Infrastructure.Data;

namespace WhiteLagoon.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;

        public VillaController(IVillaService villaService)
        {
            _villaService = villaService;
        }


        public IActionResult Index()
        {
            var villas = _villaService.GetAllVillas();  
            return View(villas);
        }
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        public IActionResult Create(Villa obj)
        {

            if (obj.Name == obj.Description)
            {
                ModelState.AddModelError("", "Name can't be the same as Description");
            }
            if(ModelState.IsValid) {    
               bool sucessCreate = _villaService.CreateVilla(obj);
                if (sucessCreate)
                {
                    TempData["success"] = "Villa is Created successfuly . ";
                    return RedirectToAction(nameof(Index));

                }     
            }

            TempData["error"] = "can't  Created Villa ";
            return View(obj);
          
        }

        #region update
        public IActionResult Update(int VillaId)
        {
            Villa? obj = _villaService.GetVillaById(VillaId);
            if (obj == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View("Update", obj);

        }
        [HttpPost]
        public IActionResult Update(Villa obj)
        {

            if (ModelState.IsValid)
            {
                bool villaUpdated = _villaService.UpdateVilla(obj);
                if (villaUpdated)
                {
                   TempData["success"] = "Villa is updated successfuly . ";
                   return RedirectToAction(nameof(Index));
                }
             
            }
            TempData["error"] = "Villa can't be update ";
            return View(obj);

        }

        #endregion
     
        public IActionResult Delete(int VillaId)
        {
            Villa? obj = _villaService.GetVillaById(VillaId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View( obj);

        }
        [HttpPost]
        public IActionResult Delete(Villa obj)
        {

            bool villaDeleted = _villaService.DeleteVilla(obj.Id);
            if (villaDeleted)
            {
                TempData["success"] = "the villa has been deleted successfuly";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                TempData["error"] = "the villa can't be deleted";
                return View(obj);
            }
           

        }

    }
}

WhiteLagoon/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Infrastructure.Repository;
using WhiteLagoon.ViewModels;

namespace WhiteLagoon.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;
        }
        public IActionResult Index()
        {
            var villaNumbers = _villaNumberService.GetAllVillaNumbers(includeProperties:"Villa");
            return View(villaNumbers);
        }


        #region Create
        public IActionResult Create()
        {
            VillaNumberVM villaNumberVM = new VillaNumberVM()
            {
                VillaList = _villaService.GetAllVillas()
                                                .Select(x => new SelectListItem
                                                {
                                                    Text = x.Name,
                                                    Value = x.Id.ToString()
                                                })
            };


            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Create(VillaNumberVM villaNumberModel)
        {
            bool roomNumberExsits = _villaNumberService.CheckVillaNumberExist(villaNumberModel.Villa_Number);
            if (ModelState.IsValid && !roomNumberExsits)
            {
                // mapping 
                VillaNumber villaNumberDb = new VillaNumber()
                {
                    Villa_Number = villaNumberModel.Villa_Number,
                    SpecialDetails = villaNumberModel.SpecialDetails,
                    Villa_id = villaNumberModel.Villa_id
                };

                bool created = _villaNumberService.CreateVillaNumber(villaNumberDb);
                if (created)
                {
                    TempData["success"] = "Villa Number Created successfly";
                    return RedirectToAction("Index");

                }

            }
            TempData["error"] = "Can't Create the Villa Number";
            if (roomNumberExsits)
            {
                TempData["error"] = "Villa Number already exists";
			}
            villaNumberModel.VillaList = _villaService.GetAllVillas()
												.Select(x => new SelectListItem
                                                {
                                                    Text = x.Name,
                                                    Value = x.Id.ToString()
                                                });

            return View(villaNumberModel);
        }
        #endregion

        #region Update
        public IActionResult Update(int villaNumberId)
        {
            var villNumberDB = _villaNumberService.GetVillaNumberById(villaNumberId);
            var villaNumberVM = new VillaNumberVM()
            {
                VillaList = _villaService.GetAllVillas().Select(x => new SelectListItem
                                                {
                                                    Text = x.Name,
                                                    Value = x.Id.ToString()
                                                }),
                Villa_Number = villNumberDB.Villa_Number,
                Villa_id = villNumberDB.Villa_id,
                SpecialDetails = villNumberDB.SpecialDetails


            };
            if (villNumberDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }
            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Update(VillaNumberVM villaNumberModel)
        {

            if (ModelState.IsValid)
            {
                // Mapping

                VillaNumber villaNumberDb = new VillaNumber()
                {
                    Villa_Number = villaNumberModel.Villa_Number,
                    SpecialDetails = villaNumberModel.SpecialDetails,
                    Villa_id = villaNumberModel.Villa_id
                };
                //Update to the database
			    bool updated =  _villaNumberService.UpdateVillaNumber(villaNumberDb);
                if (updated)
                {
                    TempData["success"] = "Villa Number Updated successfly";
                    return RedirectToAction(nameof(Index));
                }
              


            }
            TempData["error"] = "Can't Update the Villa Number";

            villaNumberModel.VillaList = _villaService.GetAllVillas()
                                                .Select(x => new SelectListItem
                                                {
                                                    Text = x.Name,
                                                    Value = x.Id.ToString()
                                                });

            return View(villaNumberModel);
        }
        #endregion

        #region Delete

        public IActionResult Delete(int villaNumberId)
        {
            var villaNumberDB = _villaNumberService.GetVillaNumberById(villaNumberId);
            var villaNumberVM = new VillaNumberVM()
            {
                VillaList = _villaService.GetAllVillas()
                                                .Select(x => new SelectListItem
                                                {
                                                    Text = x.Name,
                                                    Value = x.Id.ToString()
                                                }),
                Villa_Number = villaNumberDB.Villa_Number,
                Villa_id = villaNumberDB.Villa_id,
                SpecialDetails = villaNumberDB.SpecialDetails


            };
            if (villaNumberDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }
            return View(villaNumberVM);
        }


        [HttpPost]
        public IActionResult Delete(VillaNumberVM villaNumberModel)
        {
            bool deleted = _villaNumberService.DeleteVillaNumber(villaNumberModel.Villa_Number);

            if (deleted)
            {
                TempData["success"] = "Villa Number Deleted successfly";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "Can't Delete the Villa Number";
            return View("Delete");
        }


        #endregion

    }
           


    
}

WhiteLagoon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WhiteLagoon</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="~/WhiteLagoon.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="~/css/spinner.css" />
	<link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow>
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png"  style="width:35px"/> </a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
						</li>
						@if (User.IsInRole(SD.Role_Admin))
						{
							<li class="nav-item dropdown">
								  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Content Mangement
								  </a>

							<ul class="dropdown-menu">
									<li><a class="dropdown-item " asp-area="" asp-controller="Villa" asp-action="index">Villas</a> </li>
									<li><a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="index">Villa Number</a> </li>
									<li><hr class="dropdown-divider"></li>
									<li><a class="dropdown-item " asp-area="" asp-controller="Amenity" asp-action="index">Amenity</a> </li>
									<li><a class="dropdown-item " asp-area="" asp-controller="Booking" asp-action="index" >Booking</a> </li>
								  </ul>
						</li>
					}
					else
					{
							<a class="nav-link " asp-controller="Booking" asp-action="Index">Manage Booking</a>
					}

						
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="">
		<main role="main">
			<div class="loading spinner" style="display:none;"></div>
		   <partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer bg-dark text-muted">
		<div class="container text-center" >
			Make with <i class="bi bi-heart"></i> by Abdallah-Agag
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js" asp-append-version="true"> </script>
	@*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/WhiteLagoon.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid d-flex justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>   
                </button>
            </div>
            <partial name="_LoginPartialAdmin" />
        </nav>
    </header>
    <div class="container-fluid">
        <div class="loading spinner" style="display:none;"></div>
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
                <div class="position-static pt-3">
                    <ul class="navbar-nav">
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3">
                                Menu
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                                <span class="me-2"><i class="bi bi-speedometer2"></i></span>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3 mt-2">
                                Content Management
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Villa" asp-action="Index">
                                <span class="me-2"><i class="bi bi-house-door"></i></span>
                                <span>Villa</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="VillaNumber" asp-action="Index">
                                <span class="me-2"><i class="bi bi-list-ol"></i></i></span>
                                <span>VillaNumber</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Amenity" asp-action="Index">
                                <span class="me-2"><i class="bi bi-building"></i></span>
                                <span>Amenity</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Booking</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 w-100">
                    <partial name="_Notification" />
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

      <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center" >
            Make with <i class="bi bi-heart"></i> by Abdallah-Agag
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js" integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js" asp-append-version="true"> </script>
    @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
   @*  <script src="~/js/apexcharts.js"></script> *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/4.3.0/apexcharts.min.js" integrity="sha512-QgLS4OmTNBq9TujITTSh0jrZxZ55CFjs4wjK8NXsBoZb04UYl8wWQJNaS8jRiLq6/c60bEfOj3cPsxadHICNfw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WhiteLagoon/Views/Shared/_LoginPartialAdmin.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


<ul class="navbar-nav  d-none d-md-flex nav-login">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
        data-bs-toggle="dropdown" aria-expanded="false">
            Hello @UserManager.GetUserName(User)
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link text-center" asp-controller="Account" asp-action="Logout"> <i class="bi bi-box-arrow-left"></i> Logout</a>
        </ul>
    </li>
</ul>

WhiteLagoon/Views/Shared/_Notification.cshtml
@if (TempData["error"] is not null)
{

                    <script src="~/lib/jquery/dist/jquery.min.js"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
                    <script type ="text/javascript"> 
                                     toastr.error('@TempData["error"]')
                    </script>


}
@if (TempData["success"] is not null)
{
                        <script src="~/lib/jquery/dist/jquery.min.js"></script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
                        <script type ="text/javascript">
                                toastr.success('@TempData["success"]')

                        </script>


}

WhiteLagoon/Views/Shared/_VillaDetails.cshtml
@model Villa
<div class="row">
        <div class="col-12 col-md-5">
            <img src="@Model.ImageUrl" style="border-radius:10px;" width="100%" />
        </div>
        <div class="col-12 col-md-7">
            <div class="row p-2">
                <div class="col-12">
                        <p class="card-title text-warning" style="font-size:xx-large">@Model.Name</p>
                    <p class="card-text" style="font-size:large">
                    @Html.Raw(Model.Description)
                    </p>
                @if (Model.VillaAmenity != null && Model.VillaAmenity.Count() > 0)
                {
                                    <p class="h5 text-white">Villa Amenities</p>
                    <ul>
                        @foreach (var amenity in Model.VillaAmenity)
                        {
                                                             <li>@amenity.Name</li>
                        }
                    </ul>
                }
                </div>
            </div>
            <div class="row col-12">
                <span class="text-end p-0 pt-3 m-0">
                                <span class="float-right">Max Occupancy : @Model.Occupancy adults </span><br />
                            <span class="float-right pt-1">Villa Size : @Model.Sqft sqft</span><br />
                    <p class="text-warning font-weight-bold pt-1">
                        USD
                        <span style=" #ff6a00">
                        @Model.Price.ToString("c") / night
                        </span>
                    </p>
                </span>
            </div>
        </div>
    </div>