WhiteLagoon/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Runtime.CompilerServices;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Application.Utilities;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.ViewModels;

namespace WhiteLagoon.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AmenityController : Controller
    {
        private readonly IAmenityService _amenityService;
        private readonly IVillaService _villaService;


        public AmenityController(IAmenityService amenityService, IVillaService virillaService)
        {

            _amenityService = amenityService;
            _villaService = virillaService;
        }
        public IActionResult Index()
        {
            var amenities = _amenityService.GetAllAmenities(IncludeProperties:"Villa");
            return View(amenities);
        }
        #region Create
        public IActionResult Create()
        {
            AmenityVM model = new AmenityVM()
            {
                VillaList = VillaDropDownList()

            };
            return View("Create", model);
        }
        [HttpPost]
        public IActionResult Create(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                var amenityDB = new Amenity()
                {
                    Name = amenityVM.Name,
                    Description = amenityVM.Description,
                    VillaId = amenityVM.VillaId

                };
                bool created = _amenityService.CreateAmenity(amenityDB);
                if (created)
                {
                    TempData["success"] = "A new Amenity Created successfuly";
                    return RedirectToAction("Index");
                }
                
            }
            TempData["error"] = "can't create Amentiy";
            return View(amenityVM);
        } 
        #endregion
        public IActionResult Update(int ameityId)
        {
            var amentiyDB = _amenityService.GetAmenityById( ameityId);
            var amenityVM = new AmenityVM()
            {
                VillaList = VillaDropDownList(),
                Name = amentiyDB.Name,
                VillaId = amentiyDB.VillaId,
                Description = amentiyDB.Description


            };
            if (amentiyDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }

            return View(amenityVM);
        }


        [HttpPost]
        public IActionResult Update(AmenityVM amenityVM)
        {
            if(ModelState.IsValid)
            {
                var amenityDB = new Amenity()
                {
                    Name = amenityVM.Name,
                    Description = amenityVM.Description,
                    VillaId = amenityVM.VillaId,
                };
               bool updated =  _amenityService.UpdateAmenity(amenityDB);
                if (updated)
                {
                    TempData["success"] = "Amenity is updated successfuly";
                   return RedirectToAction(nameof(Index));
                }
            }
            TempData["error"] = "Can not Update Amenity";
            return View(amenityVM);


        }
        public IActionResult Delete(int villaId)
        {

            var amenityDB = _amenityService.GetAmenityById( villaId);
            var amenityVM = new AmenityVM()
            {
                VillaList = VillaDropDownList(),
                Description = amenityDB.Description,
                VillaId = amenityDB.VillaId,
                Name = amenityDB.Name,
                Id =  amenityDB.Id


            };
            if (amenityDB == null)
            {
                TempData["error"] = " Villa Number dosn't exists ";
                return RedirectToAction("error", "Home");
            }
            return View(amenityVM);
        }


        [HttpPost]
        public IActionResult Delete(AmenityVM amenityVM)
        {
            bool deleted = _amenityService.DeleteAmenity(amenityVM.Id);
            if (deleted)
            {
                TempData["success"] = "Villa Number Deleted successfly";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "Can't Delete the Villa Number";
            return View(amenityVM);
        }
        private IEnumerable<SelectListItem> VillaDropDownList()
        {
            return _villaService.GetAllVillas().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });

        }

    }
    
}

WhiteLagoon/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Stripe.Checkout;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIORenderer;
using Syncfusion.Pdf;
using System.Drawing;
using System.Net;
using System.Security.Claims;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Services.Interface;
using WhiteLagoon.Application.Utilities;
using WhiteLagoon.Domain.Entites;
using WhiteLagoon.Infrastructure.Repository;

namespace WhiteLagoon.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingService _bookingService;
        private IWebHostEnvironment _webHostEnvironment;
        private readonly IVillaService _villaService;
        private readonly IVillaNumberService _villaNumberService;
        private readonly UserManager<AppUser> _userManager;
        public BookingController(IWebHostEnvironment webHostEnvironment, IBookingService bookingService, IVillaService villaService, IVillaNumberService villaNumberService, UserManager<AppUser> userManager)
        {
            _webHostEnvironment = webHostEnvironment;
            _bookingService = bookingService;
            _villaService = villaService;
            _villaNumberService = villaNumberService;
            _userManager = userManager;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();  
        }
        [Authorize]
       public IActionResult FinalizeBooking(int nights , DateOnly checkInDate, int villaId)
        {
            // get the claims of the current login user
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            // get the userId
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            AppUser user = _userManager.FindByIdAsync(userId).GetAwaiter().GetResult();  

            Booking booking = new()
            {
                Nights = nights ,   
                CheckInDate = checkInDate ,
                CheckOutDate= checkInDate.AddDays(nights),
                VillaId = villaId ,
                Villa = _villaService.GetVillaById(villaId,IncludeProperties: "VillaAmenity")
                ,UserId = user.Id,
                Name = user.Name,
                Phone = user.PhoneNumber,
                Email = user.Email
                
            };
            booking.TotalCost = booking.Villa.Price * nights;
            return View(booking);
        }


        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking bookingModel)
        {
            var Villa = _villaService.GetVillaById( bookingModel.VillaId, IncludeProperties: "VillaAmenity");
            var totalCost = Villa.Price * bookingModel.Nights;
            bookingModel.Status  =SD.StatusPending;
            bookingModel.BookingDate= DateTime.Now;


            // check availablity before we submit this book
            // this scenario is when there are alot of booking and if you late in the booking may
            // some one take the final book so that the villa is not available
            // ********************************************************************
            // get only the approved bookings and the checkin (Status) these books may overlapped with my Booking
           
             if(!_villaService.IsVillaRoomAvailable(bookingModel.VillaId,bookingModel.Nights,bookingModel.CheckInDate))
             {
                TempData["error"] = "Sorry, this villa has been Sold Out";
                return RedirectToAction(nameof(FinalizeBooking), new
                {
                    nights = bookingModel.Nights,
                    villaId = Villa.Id,
                    checkInDate = bookingModel.CheckInDate

                });

             }
 
             _bookingService.CreateBooking(bookingModel);       
            //adding our custom domain
            var domain = Request.Scheme + "://" + Request.Host.Value +"/";

            // set the product info and the url if the success or cancel the payment
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"Booking/BookingConfirmation?bookingId={bookingModel.Id}",
                CancelUrl = domain + $"Booking/FinalizeBooking?nights={bookingModel.Nights}&checkInDate={bookingModel.CheckInDate}&villaId={bookingModel.VillaId}"

            };
            // if you have more than one catiogry you will use the foreach method
            options.LineItems.Add(new SessionLineItemOptions
            {
                PriceData = new SessionLineItemPriceDataOptions()
                {
                    Currency = "usd",
                    UnitAmount = (long)bookingModel.TotalCost * 100,
                    ProductData = new SessionLineItemPriceDataProductDataOptions()
                    {
                        Name = bookingModel.Name,
                        Description = "You are Welcome"
                    }


                },
                Quantity = 1
            });

            // open the session between you and the API
                      
            var service = new SessionService();
            var session = service.Create(options);

            // save the session id in the database
            _bookingService.UpdateStripePaymentId(bookingModel.Id, session.Id, session.PaymentIntentId);
           
            // get the return Url of the Payment page and redirect admin to this page
            Response.Headers.Append("Location", session.Url);
            return new StatusCodeResult(303);
            
         }
        public IActionResult BookingConfirmation(int bookingId)
        {
            // get booking form Db
            var bookingDB =  _bookingService.GetBookingById(bookingId); 
            if(bookingDB is not null)
            {
                // get the session info and then check the status of Payment 
                // if successful then you can update the Booking Status and save the PaymentIntentId
                var service = new SessionService();
                Session session = service.Get(bookingDB.StripSessionId);
                if(session.PaymentStatus== "paid")
                {
                   _bookingService.UpdateStauts(bookingDB.Id, SD.StatusApproved,0);
                    _bookingService.UpdateStripePaymentId(bookingDB.Id, session.Id, session.PaymentIntentId);
                  
                }
            }
            return View(bookingId);
        }
        public IActionResult BookingDetails(int bookingId)
        {
            var booking  =_bookingService.GetBookingById(bookingId);
            if (booking is null)
            {
                return NotFound();
            }
            if(booking.Status == SD.StatusApproved && booking.VillaNumber == 0)
            {
                booking.VillaNumbers = GetAvailableRoomsInVill(booking.VillaId);
            }

          
           
            return View(booking);
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]

        public IActionResult CheckIn(Booking bookingModel)
        {
           _bookingService.UpdateStauts(bookingModel.Id, SD.StatusCheckIn, bookingModel.VillaNumber);
       
            TempData["success"] = "Check In completed Successfully";

            return RedirectToAction(nameof(BookingDetails),new {bookingId= bookingModel.Id});

        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult CheckOut(Booking bookingModel)
        {
            _bookingService.UpdateStauts(bookingModel.Id, SD.StatusCompleted, bookingModel.VillaNumber);
            TempData["success"] = "Check out completed Successfully";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = bookingModel.Id });



        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Cancel(Booking bookingModel)
        {
            _bookingService.UpdateStauts(bookingModel.Id, SD.StatusCancelled, 0);
            TempData["error"] = " Booking Cancelled Successfully";

            return RedirectToAction(nameof(BookingDetails), new { bookingId = bookingModel.Id });

        }

        public IActionResult GenerateInvoice(int id,string downloadType)
        {
            var path = _webHostEnvironment.WebRootPath;
            WordDocument document = new WordDocument();
            var dataPath = path + @"/Exports/BookingDetails.docx";

            // load template
            FileStream stream =  new FileStream(dataPath,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);
            document.Open(stream,FormatType.Automatic); 

            // update template
            var booking  =  _bookingService.GetBookingById(id);

            TextSelection textSelection = document.Find("xx_customer_name", false, true);
            WTextRange textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.Name;

            textSelection = document.Find("xx_customer_phone", false, true);
            textRange =  textSelection.GetAsOneRange(); 
            textRange.Text  = booking.Phone;


            textSelection = document.Find("xx_customer_email", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.Email;


            textSelection = document.Find("xx_payment_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.PaymentDate.ToShortDateString();


            textSelection = document.Find("xx_checkin_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.CheckInDate.ToShortDateString();

WhiteLagoon/Views/Booking/BookingConfirmation.cshtml
@model int
<div class="container  pt-4">
    <div class="col-12 text-center">
        <h1 class="text-success text-center">Your Vacation is Confirmed!</h1>
        Your Order Number is  :  @Model<br />
        <p>You can view all order details in Manage Order Section.</p>
        <img src="~/images/orderConfirmed.jpg" style="border-radius:20px" width="65%" />
    </div>
    <div class="col-12 text-center text-warning">
        <p class="pt-1">Pack your bags! You are one step closer to an amazing vacation!</p>
    </div>

</div> 

WhiteLagoon/Views/Booking/BookingDetails.cshtml
@model Booking
<div class="p-4 mt-0 mt-lg-4">
    <div class="row" style="border: 1px solid #aaa;">

        <div class="col-12 col-lg-6 p-4 2 mt-2 mt-md-0">
            <div class="row p-1 " style="border-radius:20px; ">
                <div class="col-6">
                    <h3 class="text-success">Villa Details</h3>
                </div>
                <div class="col-6 text-end">
                    <a class="btn btn-secondary my-2" asp-action="index"><i class="bi bi-arrow-left-circle"></i> Back to Bookings</a>
                </div>
            
                <partial name="_VillaDetails" model="@Model.Villa" />
                <div class="text-end">
                    <h4 class="text-danger font-weight-bold ">
                        Booking Total :
                        <span style="border-bottom:1px solid #ff6a00">
                            @Model.TotalCost.ToString("c")
                        </span>
                    </h4>
                </div>


                <hr />
                <form method="post">
                   <div class="row pt-1 mb-3" style="border-radius:20px;">
                       <div class="col-12 text-center">
                            <button asp-action="GenerateInvoice" asp-controller="Booking" asp-route-id=@Model.Id  asp-route-downloadType="word" type="submit"
                                class="btn btn-sm btn-secondary my-1">
                                 
                                <i class="bi bi-file-earmark-word"></i> Generate Invoice (word)

                            </button>

                             <button asp-action="GenerateInvoice" asp-controller="Booking" asp-route-id=@Model.Id asp-route-downloadType="pdf" type="submit"
                                class="btn btn-sm btn-secondary my-1">

                                <i class="bi bi-filetype-pdf"></i> Generate Invoice (pdf)

                            </button>
                       </div>
                   </div>
                </form>

            </div>
        </div>
        <div class="col-12 col-lg-6 p-4 2 mt-4 mt-md-0" style="border-left:1px solid #aaa">
            <form method="post">

                <div class="row pt-1 mb-3 " style="border-radius:20px; ">
                    <div class="col-6">
                        <h3 class="text-success">Enter Booking Details</h3>
                    </div>
                    @if (User.IsInRole(SD.Role_Admin) && (Model.Status==SD.StatusPending|| Model.Status == SD.StatusApproved))
                    {
                        <div class="col-6">
                            <button type="submit" asp-action="Cancel" asp-controller="Booking" class="btn btn-sm btn-outline-danger form-control my-1"><i class="bi bi-x-circle"></i> &nbsp; Cancel Booking</button>
                        </div>
                    }
                  
                </div>
                <div class="row">
                    <div class="form-group pt-2 col-6">
                        <input asp-for="VillaId"hidden />
                        <input asp-for="Nights"hidden />
                        <input asp-for="CheckInDate"hidden />
                        <input asp-for="Status"hidden />
                        <input asp-for="UserId"hidden />
                        <input asp-for="Id"hidden />
                        
                 
                        <label class="text-warning">Name</label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Phone</label>
                        <input  asp-for="Phone"  class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Email</label>
                        <input  asp-for="Email" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Check in Date</label>
                        <input disabled  asp-for="CheckInDate"  class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Check Out Date</label>
                        <input disabled asp-for="CheckOutDate"  class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">No. of nights</label>
                        <input disabled  asp-for="Nights" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Status</label>
                        <input disabled  asp-for="Status"  class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Booking Date</label>
                        <input disabled  asp-for="BookingDate" class="form-control" />
                    </div>
                    @if(Model.Status==SD.StatusApproved )
                    {
                        <div class="form-group pt-2 col-6">
                              <label class="text-danger" asp-for="VillaNumber"></label>
                           
                                <select  class="form-select"asp-for="VillaNumber">
                                <option value="" disabled selected>---Select Room----</option>
                                @foreach (var item in Model.VillaNumbers)
                                {

                                    <option value="@item.Villa_Number">@item.Villa_Number</option>
                                }
                                </select>
                        </div>
                    }

                    else
                    {
                        @if(Model.Status == SD.StatusCheckIn || Model.Status == SD.StatusCompleted)
                            {
                                <input asp-for="VillaNumber"hidden />  
                                <div class="form-group pt-2 col-6">
                                    <label class="text-warning">Villa Number</label>
                                    <input disabled  asp-for="VillaNumber" class="form-control" />
                                </div>

                        }
                    }
                    
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Actual Check-out Date</label>
                        <input disabled  asp-for="ActualCheckOutDate" class="form-control" />
                    </div>
                    @if (User.IsInRole(SD.Role_Admin) && Model.IsPaymentSuccessful)
                    {
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Stripe PaymentIntent Id</label>
                            <input disabled asp-for="StripPaymentIntentId" class="form-control" />
                        </div>
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Stripe Session Id</label>
                            <input disabled asp-for="StripSessionId" class="form-control" />
                        </div>
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Payment Date</label>
                            <input disabled asp-for="PaymentDate" class="form-control" />
                        </div>
                    }
                       <div class="form-group pt-2 col-6">
                            <label class="text-warning">Status</label>
                            <input disabled asp-for="Status" class="form-control" />
                        </div>
                  

                </div>
                @if (User.IsInRole(SD.Role_Admin))
                {
                    <div class="form-group pt-2 pt-md-4">
                        @if (Model.Status == SD.StatusApproved)
                        {
                            <button type="submit" asp-action="CheckIn" asp-controller="Booking" class="btn btn-warning form-control my-1"><i class="bi bi-check2-square"></i> &nbsp; Check In</button>
   
                        }
                        @if(Model.Status == SD.StatusCheckIn)
                        {
                            <button type="submit"asp-action="CheckOut" asp-controller="Booking" class="btn btn-success form-control my-1"><i class="bi bi-clipboard2-check"></i> &nbsp; Check Out / Complete Booking</button>
                        }
                    </div>
                    
                }
               
            </form>
        </div>
    </div>
</div>

WhiteLagoon/Views/Booking/Index.cshtml
@{
    // use to check the status and then
        // if yoy toggile the
    var status = Context.Request.Query["status"];

    var pending = "";
    var approved = "";
    var completed = "";
    var checkIn = "";
    var canceled = "";

    switch (status)
    {
        case SD.StatusPending:
            pending = "text-white bg-success";
            break;

        case SD.StatusApproved:
            approved = "text-white bg-success";
            break;
        case SD.StatusCompleted:
            completed = "text-white bg-success";
            break;
        case SD.StatusCheckIn:
            checkIn = "text-white bg-success";
            break;
        case SD.StatusCancelled:
            canceled = "text-white bg-success";
            break;

    }
}



<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Booking List</h2>
            </div>
        </div>
    </div>

    <div class="card-body border p-4">
        <div class="row pb-3">
       
        </div>
        <table id="tblBookings" class="table table-bordered table-striped">

            <div class="d-flex justify-content-end pb-4 pt-2">
                <ul class="list-group list-group-horizontal-sm">
                    <a style="text-decoration:none;" asp-controller="Booking" asp-action="Index"
                        asp-route-status="@SD.StatusPending">
                        <li class="list-group-item @pending"> @SD.StatusPending </li>
                    </a>

                    <a style="text-decoration:none;" asp-controller="Booking" asp-action="Index"
                    asp-route-status="@SD.StatusApproved">
                    <li class="list-group-item @approved"> @SD.StatusApproved </li>
                    </a>
                    <a style="text-decoration:none;" asp-controller="Booking" asp-action="Index"
                    asp-route-status="@SD.StatusCheckIn">
                    <li class="list-group-item @checkIn"> @SD.StatusCheckIn </li>
                    </a>  
                    <a style="text-decoration:none;" asp-controller="Booking" asp-action="Index"
                        asp-route-status="@SD.StatusCompleted">
                        <li class="list-group-item @completed"> @SD.StatusCompleted </li>
                    </a>  
                    <a style="text-decoration:none;" asp-controller="Booking" asp-action="Index"
                        asp-route-status="@SD.StatusCancelled">
                        <li class="list-group-item @canceled"> @SD.StatusCancelled </li>
                    </a>
                </ul>
            </div>

            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Check In Date</th>
                    <th>Nights</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
               @*  @foreach (var item in Model)
                {
                                <tr>
                                    <td>@item.Villa.Name</td>
                                    <td>@item.Name</td>
                                    <td>@item.Description</td>
                                    <td>
                                        <div  class="w-75 btn-group" role="group" > 

                                                    <a asp-action="Update" asp-controller="Amenity" asp-route-ameityId="@item.Id"
                                                    class="btn btn-success mx-2">
                                                    <i class="bi bi-pencil-square"></i>
                                                    Edit
                                                </a>


                                                    <a asp-action="Delete" asp-controller="Amenity" asp-route-villaId="@item.Id"
                                                    class="btn btn-danger mx-2">
                                                        <i class="bi bi-trash-fill"></i>   Delete

                                                </a>
                                        </div>
                                    </td>
                                </tr>
                } *@
            </tbody>
        </table>
    </div>
</div>
@section scripts{
    <script src="~/js/Booking.js"></script>
}